# Generated by Django 6.0.3 on 2026-04-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='credit_score',
        ),
        migrations.RemoveField(
            model_name='application',
            name='identity_verified',
        ),
        migrations.AddField(
            model_name='application',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('business_owner', 'Business Owner'), ('student', 'Student'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
