# Generated by Django 5.2.12 on 2026-04-02 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name_plural": "Amenities",
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("2bed", "2 Bedroom Flat"),
                            ("1bed", "1 Bedroom Studio"),
                            ("self-con", "Self-Con Apartment"),
                            ("duplex", "Duplex"),
                            ("mini-flat", "Mini Flat"),
                            ("bungalow", "Bungalow"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "price_per_year",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("bedrooms", models.PositiveIntegerField(default=1)),
                ("bathrooms", models.PositiveIntegerField(default=1)),
                ("sqft", models.PositiveIntegerField(blank=True, null=True)),
                ("age", models.CharField(default="New", max_length=20)),
                ("description", models.TextField()),
                ("image_url", models.URLField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="property_images/"
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "landlord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Properties",
            },
        ),
        migrations.CreateModel(
            name="PropertyAmenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.amenity",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenities",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Property Amenities",
            },
        ),
    ]
