# Generated by Django 6.0.3 on 2026-04-06 07:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('properties', '0002_property_latitude_property_longitude_propertyimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('tenant', 'landlord', 'rental_property')},
        ),
    ]
