# Generated by Django 6.0.3 on 2026-04-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingrequest',
            name='gateway',
            field=models.CharField(blank=True, choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], default='paystack', max_length=15),
        ),
        migrations.AddField(
            model_name='fundingrequest',
            name='gateway_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fundingrequest',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
