# Generated by Django 6.0.3 on 2026-04-06 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('application_received', 'New Application'), ('application_approved', 'Application Approved'), ('application_rejected', 'Application Rejected'), ('message_received', 'New Message'), ('payment_confirmed', 'Payment Confirmed'), ('lease_created', 'Lease Created'), ('rent_due', 'Rent Due'), ('system', 'System')], default='system', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
